name: Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 24.x
              uses: actions/setup-node@v4
              with:
                  node-version: 24.x
                  cache: "npm"

            - run: npm install

            - run: npm run build

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      main.js
                      manifest.json
                      styles.css
